version: '3'
services:
  web:
    build:
      context: "."
      dockerfile: ./Dockerfile
      args:
        SHARP_DIST_BASE_URL: "https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz"
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
