version: '3'
services:
  web:
    build:
      context: "."
      dockerfile: ./Dockerfile
    image: node:alpine
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
